import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Footer, Nav } from "@/components/layout";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata = {
    title: "Amazon clone",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={font.className}>
            <body>
                <Nav />

                <main>{children}</main>

                <Footer />
            </body>
        </html>
    );
}
